### PR TITLE
Added Thorny Uber

### PR DESCRIPTION
**Pull request by mdovwagner**
Do it

### CODE REVIEW

**Comment by mdovwagner** [comment]
I fixed everything (updated winnerIDs and the packages maybe)

**Comment by sillle14** [comment]
Still seems like 0.1.1 won't install for me. (missing `react-d3-graph`)

**Comment by sillle14** [comment]
Still breaking, I think it's missing player count min and max. You should set up a mongo and test it locally.

**Review by sillle14 — COMMENTED** [review]
Why is the package-lock diff so huge?

**Review by sillle14 — APPROVED** [review]

**Pull request merged**
